### ISSUE TITLE
i am unanle to install GoogleSingIn-SuiteCRM

### ISSUE THREAD

**Issue by tahiraqt** [ChangezKhan/GoogleSignIn-SuiteCRM#3]
i am trying to install this plugin but getting error i.e
ZIP Error(0): Status(9): Arhive(upload://GoogleSignIn-SuiteCRM-master.zip): Directory(/tmp/yyzUH1)

Please help to resolve this issue.

Kind Regards!

**Comment by ChangezKhan** [comment]
OK, let me check. I'll update you on this soon.

**Comment by ChangezKhan** [comment]
@tahiraqt, I have updated `Releases` section. Kindly find the below picture and then download the zip file while is highlighted in the red box.

![Install GoogleSignIn Release](https://raw.githubusercontent.com/changezkhan/crm/master/google_sign_in_release.JPG)

Kindly let me know if it works for you or not.

**Comment by tahiraqt** [comment]
Thank You

**Comment by ChangezKhan** [comment]
@tahiraqt no need to say "sir". We all are equal here in the ocean of "Open Source".
